spring:
  cloud:
    stream:
      function:
        definition : paymentProcessor1
      bindings:
        paymentProcessor1-in-0 :
          destination: order-event
        paymentProcessor1-out-0:
          destination: payment-event


server:
  port: 8082