eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 9001
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: HelloService1
        uri: lb://service1
        predicates:
        - Path=/helloservice1/**
      - id: HelloService2
        uri: lb://service2
        predicates:
        - Path=/helloservice2/**
        
        
